spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: book-store
      username: rootuser
      password: rootpass
      auto-index-creation: true
